// Generated by CoffeeScript 1.7.1
(function() {
  var Calculator, calculator;

  Calculator = Backbone.View.extend({
    el: $("body"),
    timer: null,
    currentChars: "",
    prevValidInput: "",
    prevValidClickInput: "",
    textbox: $(".tb"),
    answerBox: $(".question"),
    events: {
      keypress: "debounce",
      "click .key": "onKeyClick"
    },
    initialize: function() {
      _.bindAll(this, "debounce");
    },
    debounce: function(e) {
      var ch;
      ch = void 0;
      if (this.timer) {
        clearTimeout(this.timer);
      }
      ch = String.fromCharCode(e.keyCode);
      this.currentChars = this.currentChars + ch;
      return this.timer = setTimeout(_.bind(this.callback, this), 300, this.currentChars);
    },
    callback: function(currentChars) {
      return this.onTextEnter(currentChars);
    },
    processKeyInput: function(chars) {
      chars = chars.replace(/[^0-9 +-.*/]/g, "");
      return this.prevValidInput = chars.replace(/^[+-.*0\s/]+|[+-.*\s/]+$/g, "");
    },
    onTextEnter: function(currentChars) {
      var f, lastChar;
      f = void 0;
      lastChar = void 0;
      this.processKeyInput(currentChars);
      console.log("prevValidInput: " + this.prevValidInput);
      f = new Function("return " + this.prevValidInput);
      lastChar = currentChars.slice(-1);
      if (lastChar !== "+" && lastChar !== "-" && lastChar !== "*" && lastChar !== "/" && lastChar !== ".") {
        this.textbox.val(f());
      }
      return this.answerBox.html(this.prevValidInput + " =");
    },
    reset: function() {
      this.currentChars = "";
      this.prevValidInput = "";
      this.prevValidClickInput = "";
      this.timer = null;
      this.textbox.val("");
      return this.answerBox.html("");
    },
    processClickInput: function(chars) {
      chars = chars.replace(/[^0-9 +-.*=/]/g, "");
      return this.prevValidClickInput = chars.replace(/^[0\s]+|[\s]+/g, "");
    },
    onKeyClick: function(ev) {
      var currentValue, f, input;
      currentValue = void 0;
      f = void 0;
      input = void 0;
      currentValue = $(".tb").val();
      input = $(ev.target).text().trim();
      if (input === "=") {
        this.processClickInput(currentValue);
        f = new Function("return " + this.prevValidClickInput);
        this.textbox.val(f());
      } else if (input === "AC") {
        return this.reset();
      } else {
        this.processClickInput(currentValue + input);
        this.textbox.val(this.prevValidClickInput);
      }
      return this.answerBox.html(this.prevValidClickInput + " =");
    }
  });

  calculator = new Calculator();

}).call(this);
