// Generated by CoffeeScript 1.7.1
(function() {
  describe('CalculatorTest', function() {
    var calculator;
    calculator = new Calculator();
    it('test process click should echo input', function() {
      var result;
      result = calculator.processClickInput("123");
      return expect(result).toBe("123");
    });
    it('test process click should filter input-alphabet', function() {
      var result;
      result = calculator.processClickInput("123randomtextwhichisnotallowed");
      return expect(result).toBe("123");
    });
    it('test process click should allow arithmetic operations', function() {
      var result;
      result = calculator.processClickInput("1+2+3+4");
      return expect(result).toBe("1+2+3+4");
    });
    it('test process click should remove leading 0 and trailing spaces', function() {
      var result;
      result = calculator.processClickInput(" 01+2+3+4 ");
      return expect(result).toBe("1+2+3+4");
    });
    it('test process key should echo input', function() {
      var result;
      result = calculator.processKeyInput("123");
      return expect(result).toBe("123");
    });
    it('test process key should filter input-alphabet', function() {
      var result;
      result = calculator.processKeyInput("123randomtextwhichisnotallowed");
      return expect(result).toBe("123");
    });
    it('test process key should allow arithmetic operations', function() {
      var result;
      result = calculator.processKeyInput("1+2+3+4");
      return expect(result).toBe("1+2+3+4");
    });
    return it('test process key should remove leading 0 and trailing spaces', function() {
      var result;
      result = calculator.processKeyInput(" 01+2+3+4 ");
      return expect(result).toBe("1+2+3+4");
    });
  });

}).call(this);
