// Generated by CoffeeScript 1.7.1
(function() {
  (window.Calculator = function() {
    var answerBox, callback, currentChars, debounce, onKeyClick, onTextEnter, prevValidClickInput, prevValidInput, processClickInput, processKeyInput, reset, textbox, timer;
    timer = void 0;
    currentChars = "";
    prevValidInput = "";
    prevValidClickInput = "";
    textbox = $(".tb");
    answerBox = $(".question");
    debounce = function(e) {
      var ch;
      if (timer) {
        clearTimeout(timer);
      }
      ch = String.fromCharCode(e.keyCode);
      currentChars = currentChars + ch;
      return timer = setTimeout(callback, 300, currentChars);
    };
    callback = function(currentChars) {
      return onTextEnter(currentChars);
    };
    processKeyInput = function(chars) {
      chars = chars.replace(/[^0-9 +-.*/]/ig, '');
      return prevValidInput = chars.replace(/^[+-.*0\s/]+|[+-.*\s/]+$/g, '');
    };
    onTextEnter = function(currentChars) {
      var f, lastChar;
      processKeyInput(currentChars);
      console.log("prevValidInput: " + prevValidInput);
      f = new Function("return " + prevValidInput);
      lastChar = currentChars.slice(-1);
      if (lastChar !== "+" && lastChar !== "-" && lastChar !== "*" && lastChar !== "/" && lastChar !== ".") {
        textbox.val(f());
      }
      return answerBox.html(prevValidInput + " =");
    };
    textbox.on("keypress", debounce);
    reset = function() {
      currentChars = "";
      prevValidInput = "";
      prevValidClickInput = "";
      timer = void 0;
      textbox.val("");
      return answerBox.html("");
    };
    processClickInput = function(chars) {
      chars = chars.replace(/[^0-9 +-.*=/]/ig, '');
      return prevValidClickInput = chars.replace(/^[0\s]+|[\s]+/g, '');
    };
    onKeyClick = function() {
      var currentValue, f, input;
      currentValue = $(".tb").val();
      input = $(this).text().trim();
      if (input === "=") {
        processClickInput(currentValue);
        f = new Function("return " + prevValidClickInput);
        textbox.val(f());
      } else if (input === "AC") {
        return reset();
      } else {
        processClickInput(currentValue + input);
        textbox.val(prevValidClickInput);
      }
      return answerBox.html(prevValidClickInput + " =");
    };
    $(".key").on("click", onKeyClick);
    return {
      processClickInput: processClickInput,
      reset: reset,
      processKeyInput: processKeyInput,
      onTextEnter: onTextEnter,
      callback: callback
    };
  })();

}).call(this);
